api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path("", views.get_routes),
    path("projects/", views.get_projects),
    path("projects/<str:pk>/", views.get_project),
    path("projects/<str:pk>/vote/", views.project_vote),
    path(
        "users/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"
    ),
    path(
        "users/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"
    ),
    path("remove-tag/", views.remove_tag)
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("projects.urls", namespace="projects")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("api/", include("api.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name="reset/reset_password.html"
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset/reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",  # by default
        auth_views.PasswordResetConfirmView.as_view(
            template_name="reset/reset_password_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",  # by default
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset/reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"

urlpatterns = [
    path(
        "",
        views.projects,
        name="projects",
    ),
    path(
        "project/<str:pk>/",
        views.project,
        name="project",
    ),
    path(
        "create_project/",
        views.create_project,
        name="create_project",
    ),
    path(
        "update_project/<str:pk>/",
        views.update_project,
        name="update_project",
    ),
    path(
        "delete_project/<str:pk>/",
        views.delete_project,
        name="delete_project",
    ),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"


urlpatterns = [
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
    path("", views.profiles, name="profiles"),
    path("profile/<str:pk>", views.user_profile, name="user_profile"),
    path("account/", views.user_account, name="user_account"),
    path("edit_account/", views.edit_account, name="edit_account"),
    path("create_skill/", views.create_skill, name="create_skill"),
    path("update_skill/<str:pk>/", views.update_skill, name="update_skill"),
    path("delete_skill/<str:pk>/", views.delete_skill, name="delete_skill"),
    path("inbox/", views.inbox, name="inbox"),
    path("message/<str:pk>/", views.view_message, name="message"),
    path(
        "create_message/<str:pk>/", views.create_message, name="create_message"
    ),

]

templates/partials/_footer.html
<header class="header">
  <center>
    <span style="color:red">Ya</span>.2022
  </center>
</header>

templates/partials/_navbar.html
{% load static %}
<header class="header">
  <div class="container container--narrow">
    <a class="navbar-brand" href="{% url 'projects:projects' %}">
      <span style="color:red">Ya</span>tube
    </a>
    <nav class="header__nav">
      <input type="checkbox" id="responsive-menu" />
      <label for="responsive-menu" class="toggle-menu">
        <span>Menu</span>
        <div class="toggle-menu__lines"></div>
      </label>
      <ul class="header__menu">
        <li class="header__menuItem"><a href="{% url 'users:profiles' %}">Users</a></li>
        <li class="header__menuItem"><a href="{% url 'projects:projects' %}">Posts</a></li>
        
        {% if request.user.is_authenticated %}
          <li class="header__menuItem"><a href="{% url 'users:inbox' %}">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'users:user_account' %}">Account</a></li>
          <li class="header__menuItem"><a href="{% url 'users:logout' %}" class="btn btn--sub">Logout</a></li>
        {% else %}
          <li class="header__menuItem"><a href="{% url 'users:login' %}" class="btn btn--sub">Login/Sign Up</a></li>
        {% endif %}
        </ul>
    </nav>
  </div>
</header>