api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path("", views.get_routes),
    path("projects/", views.get_projects),
    path("projects/<str:pk>/", views.get_project),
    path("projects/<str:pk>/vote/", views.project_vote),
    path(
        "users/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"
    ),
    path(
        "users/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"
    ),
    path("remove-tag/", views.remove_tag)
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("projects.urls", namespace="projects")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("api/", include("api.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name="reset/reset_password.html"
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset/reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",  # by default
        auth_views.PasswordResetConfirmView.as_view(
            template_name="reset/reset_password_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",  # by default
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset/reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"

urlpatterns = [
    path(
        "",
        views.projects,
        name="projects",
    ),
    path(
        "project/<str:pk>/",
        views.project,
        name="project",
    ),
    path(
        "create_project/",
        views.create_project,
        name="create_project",
    ),
    path(
        "update_project/<str:pk>/",
        views.update_project,
        name="update_project",
    ),
    path(
        "delete_project/<str:pk>/",
        views.delete_project,
        name="delete_project",
    ),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"


urlpatterns = [
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
    path("", views.profiles, name="profiles"),
    path("profile/<str:pk>", views.user_profile, name="user_profile"),
    path("account/", views.user_account, name="user_account"),
    path("edit_account/", views.edit_account, name="edit_account"),
    path("create_skill/", views.create_skill, name="create_skill"),
    path("update_skill/<str:pk>/", views.update_skill, name="update_skill"),
    path("delete_skill/<str:pk>/", views.delete_skill, name="delete_skill"),
    path("inbox/", views.inbox, name="inbox"),
    path("message/<str:pk>/", views.view_message, name="message"),
    path(
        "create_message/<str:pk>/", views.create_message, name="create_message"
    ),

]

projects/models.py
from django.db import models
import uuid
from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(
        null=True, blank=True, default="default.jpg"
    )
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField("Tag", blank=True)  # "" - bcs Tag below
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = (
            "-vote_ratio",
            "-vote_total",
            "-created",
        )

    @property
    def image_url(self):
        try:
            url = self.featured_image.url
        except:
            url = ""
        return url


    # делаем лист, чтобы проверить, можем ли мы оставить ревью
    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list("owner__id", flat=True)
        return queryset

    @property
    def get_vote_count(self):
        reviews = self.review_set.all()
        up_votes = reviews.filter(value="up").count()
        total_votes = reviews.count()
        ratio = (up_votes / total_votes) * 100
        self.vote_total = total_votes
        self.vote_ratio = ratio
        self.save()


# comment
class Review(models.Model):
    VOTE_TYPE = (
        ("up", "Up vote"),
        ("down", "Down vote"),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # благодаря этому, только 1 ревью можно оставить
    class Meta:
        unique_together = [["owner", "project"]]
        ordering = ("-created",)

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.name


# class Follow(models.Model):
#     user = models.ForeignKey(
#         User,
#         on_delete=models.CASCADE,
#         related_name="follower",
#         verbose_name="Сталкер",
#     )
#     author = models.ForeignKey(
#         User,
#         on_delete=models.CASCADE,
#         related_name="following",
#         verbose_name="Тот кого сталкерят",
#     )

#     class Meta:
#         verbose_name = "Подписка"
#         verbose_name_plural = "Подписки"
#         constraints = models.UniqueConstraint(
#             fields=["user", "author"],
#             name="unique_followers",
#         )

users/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True
    )
    name = models.CharField(max_length=200, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    short_intro = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(
        null=True,
        blank=True,
        upload_to="profiles/",
        default="profiles/user-default.png",
    )
    social_github = models.CharField(max_length=200, null=True, blank=True)
    social_vk = models.CharField(max_length=200, null=True, blank=True)
    social_telegram = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return str(self.user.username)

    class Meta:
        ordering = (
            "created",
        )

    # в except нужно будет добавить картинку
    @property
    def image_url(self):
        try:
            url = self.profile_image.url
        except:
            url = ""
        return url


class Skill(models.Model):
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True
    )
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return str(self.name)


class Message(models.Model):
    sender = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    recipient = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="messages",
    )
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    is_read = models.BooleanField(default=False, null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        primary_key=True, unique=True, default=uuid.uuid4, editable=False
    )

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ["is_read", "-created"]

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.models import User
from .forms import CustomUserCreationForm, ProfileForm, SkillForm, MessageForm
from django.core.mail import send_mail

from .utils import search_profiles, paginator_profiles
from .models import Profile, Message


def login_user(request):
    page = "login"
    if request.user.is_authenticated:
        return redirect("users:profiles")

    if request.method == "POST":
        # добавили lower так как в регистрации преобразуется в lower
        username = request.POST["username"].lower()
        password = request.POST["password"]
        # проверяем, что существует
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "Username does not exists")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # сперва сделать
            # href - href="{% url 'users:login' %}?next={{ request.path }}"
            # с помощью этого, там где Login_required будет перенаправлять
            # на next, в template action = "" указать пустым
            return redirect(
                request.GET["next"]
                if "next" in request.GET
                else "users:user_account"
            )
        else:
            messages.error(request, "Username OR password is incorrect")
    return render(request, "users/login_register.html")


def logout_user(request):
    logout(request)
    messages.success(request, "User was logged out!")
    return redirect("users:login")


def register_user(request):
    page = "register"
    form = CustomUserCreationForm()
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, "User account was created!")
            login(request, user)
            return redirect("users:edit_account")
        else:
            messages.error(
                request, "An error has occurred during registration"
            )

    context = {"page": page, "form": form}
    return render(request, "users/login_register.html", context)


def profiles(request):
    profiles, search_query = search_profiles(request)
    custom_range, profiles = paginator_profiles(request, profiles, 3)
    context = {
        "profiles": profiles,
        "search_query": search_query,
        "custom_range": custom_range,
    }
    return render(request, "users/profiles.html", context)


def user_profile(request, pk):
    profile = Profile.objects.get(id=pk)
    # то есть исключаем скилы у которых нету описания
    top_skills = profile.skill_set.exclude(description__exact="")
    other_skills = profile.skill_set.filter(description="")
    context = {
        "profile": profile,
        "top_skills": top_skills,
        "other_skills": other_skills,
    }
    return render(request, "users/user_profile.html", context)


@login_required(login_url="users:login")
def user_account(request):
    profile = request.user.profile
    skills = profile.skill_set.all()
    projects = profile.project_set.all()

    context = {
        "profile": profile,
        "skills": skills,
        "projects": projects,
    }
    return render(request, "users/account.html", context)


@login_required(login_url="users:login")
def edit_account(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)
    if request.method == "POST":
        form = ProfileForm(
            request.POST or None,
            files=request.FILES or None,
            instance=profile,
        )
        if form.is_valid():
            form.save()
            return redirect("users:user_account")
        else:
            messages.error(request, "Something wrong!")
    context = {"form": form}
    return render(request, "users/profile_form.html", context)


@login_required(login_url="users:login")
def create_skill(request):
    profile = request.user.profile
    form = SkillForm()
    if request.method == "POST":
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = profile
            skill.save()
            messages.success(request, "Skill was added successfully")
            return redirect("users:user_account")
    context = {"form": form}
    return render(request, "users/skill_form.html", context)


@login_required(login_url="users:login")
def update_skill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    form = SkillForm(instance=skill)
    if request.method == "POST":
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            messages.success(request, "Skill was updated successfully")
            return redirect("users:user_account")
    context = {"form": form}
    return render(request, "users/skill_form.html", context)


@login_required(login_url="users:login")
def delete_skill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    if request.method == "POST":
        skill.delete()
        messages.success(request, "Skill was deleted successfully")
        return redirect("users:user_account")
    context = {"object": skill}
    return render(request, "delete_object.html", context)


@login_required(login_url="users:login")
def inbox(request):
    profile = request.user.profile
    # обращение по related name
    message_request = profile.messages.all()
    unread_count = message_request.filter(is_read=False).count()
    context = {
        "message_request": message_request,
        "unread_count": unread_count,
    }
    return render(request, "users/inbox.html", context)


@login_required(login_url="users:login")
def view_message(request, pk):
    profile = request.user.profile
    message = profile.messages.get(id=pk)
    if not message.is_read:
        message.is_read = True
        message.save()
    context = {"message": message}
    return render(request, "users/message.html", context)


# @login_required(login_url="users:login")
def create_message(request, pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()
    try:
        sender = request.user.profile
    except:
        sender = None
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient
            if sender:
                message.name = sender.name
                message.email = sender.email
            message.save()
            messages.success(request, "Your message was successfully sent!")
            return redirect("users:user_profile", recipient.id)
    context = {"recipient": recipient, "form": form}
    return render(request, "users/message_form.html", context)

users/templates/users/account.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:edit_account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{ profile.image_url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>
              {% if profile.short_intro %}
              <p class="dev__title">{{ profile.short_intro }}</p>
              {% endif %}
              {% if profile.location %}
              <p class="dev__location">Based in {{ profile.location }}</p>
              {% endif %}

                {% comment %}   
                <ul class="dev__social">
                  <li>
                    <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
                  </li>
                  <li>
                    <a title="Stackoverflow" href="#" target="_blank"><i class="im im-stackoverflow"></i></a>
                  </li>
                </ul> 
                {% endcomment %}

          {% comment %}     <a href="#" class="btn btn--sub btn--lg">Send Message </a> {% endcomment %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio }}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'users:create_skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for skill in skills %}
            <tr>
              <td class="settings__tableInfo">
                <h4>
                  {{ skill.name }}
                </h4>
                
                <p>
                  {{ skill.description }}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:update_skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:delete_skill' skill.id %}?next=/users/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
          </table>
          <div class="settings">
            <h3 class="settings__title">Posts</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'projects:create_project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>
          <table class="settings__table">
            {% for project in projects %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'projects:project' project.id %}">
                  {% if project.featured_image %}
                    <img class="project__thumbnail" src="{{ project.image_url }}" alt="project thumbnail" />
                  {% else %}
                    <img class="project__thumbnail" src="{% static 'images/12.jpg' %}" alt="project thumbnail" />
                  {% endif %}
                </a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'projects:project' project.id %}">
                  {{ project.title }}
                </a>
                <p>
                  {{ project.description|slice:"100" }}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:update_project' project.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:delete_project' project.id %}?next=/users/account"><i class="im im-x-mark-circle-o"></i>
                  Delete
                </a>
              </td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

users/templates/users/inbox.html
{% extends "base.html" %}
{% block content %}
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">New Messages(<span>{{ unread_count }}</span>)</h3>
    <ul class="messages">
      {% for message in message_request %}
      {% if message.is_read == False%}
      <li class="message message--unread">
        {% else %}
      <li class="message message--read">
        {% endif %}
        <a href="{% url 'users:message' message.id %}">
          <span class="message__author">{{ message.name }}</span>
          <span class="message__subject">{{ message.subject }}</span>
          <span class="message__date">{{ message.created }}</span>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
</main>
</body>
{% endblock content %}

users/templates/users/login_register.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  {% if page == "register" %}
    <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/fav_y.png' %}" width="48" height="48" alt="icon" />
          </a>
          <h3>Register an Account</h3>
          <p>Create a new account</p>
        </div>
        <form method="POST" action="{% url 'users:register' %}" class="form auth__form">
          {% csrf_token %}
          {% for field in form %}
            <div class="form__field">
              <label for="formInput#text">{{ field.label }}</label>
              {{ field }}
{% comment %}               {% if field.help_text %}
                <small>{{ field.help_text }}</small>
              {% endif %} {% endcomment %}
              {% for error in field.errors %}
                <p style="color: red;">{{ error }}</p>
              {% endfor %}
            </div>
          {% endfor %}
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
          </div>
        </form>
        <div class="auth__alternative">
          <p>Already have an Account?</p>
          <a href="{% url 'users:login' %}">Log In</a>
        </div>
      </div>
    </div>
  {% else %}
    <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/fav_y.png' %}" width="48" height="48" alt="icon" />
          </a>
          <h3>Account Login</h3>
          <p>Hello, Welcome Back!</p>
        </div>
        <form method="POST" action="" class="form auth__form">
          {% csrf_token %}
          <div class="form__field">
            <label for="formInput#text">Username: </label>
            <input
              class="input input--text"
              id="formInput#text"
              type="text"
              name="username"
              placeholder="Enter your username..."
            />
          </div>
          <div class="form__field">
            <label for="formInput#password">Password: </label>
            <input
              class="input input--password"
              id="formInput#passowrd"
              type="password"
              name="password"
              placeholder="••••••••"
            />
          </div>
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
            <a href="{% url 'reset_password' %}">Forget Password?</a>
          </div>
        </form>
        <div class="auth__alternative">
          <p>Don’t have an Account?</p>
          <a href="{% url 'users:register' %}">Sign Up</a>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock content %}

users/templates/users/message.html
{% extends "base.html" %}
{% block content %}
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'users:inbox' %}">⇐</a>
        <h2 class="message__subject">{{ message.subject }}</h4>
          {% if message.sender.id%}
            <a href="{% url 'users:user_profile' message.sender.id %}" class="message__author">{{ message.name }}</a>
          {% else %}
          <p class="message__author">{{ message.name }} user was deleted</p>
          {% endif %}
          <p class="message__date">{{ message.created }}</p>
          <div class="message__body">
            {{ message.body|linebreaksbr }}
          </div>
      </div>
    </div>
  </main>
{% endblock content %}

users/templates/users/message_form.html
{% extends "base.html" %}
{% block content %}
  <main class="formPage my-xl">
    <div class="content-box">
      <div class="formWrapper">
        <a class="backButton" href="{% url 'users:user_profile' recipient.id %}">⇐</a>
        <br>
        <form class="form" method="POST">
          {% csrf_token %}
          {% if request.user.is_authenticated == False %}
            <div class="form__field">
              <label for="formInput#text">{{ form.name.label }}</label>
              {{ form.name }}
            </div>
            <div class="form__field">
              <label for="formInput#text">{{ form.email.label }}</label>
              {{ form.email }}
            </div>
          {% endif %}
          <div class="form__field">
            <label for="formInput#text">{{ form.subject.label }}</label>
            {{ form.subject }}
          </div>
          <div class="form__field">
            <label for="formInput#text">{{ form.body.label }}</label>
            {{ form.body }}
          </div>
          <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
        </form>
      </div>
    </div>
  </main>
{% endblock content %}

users/templates/users/user_profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<main class="profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <img class="avatar avatar--xl" src="{{ profile.image_url }}" />
            <h2 class="dev__name">{{ profile.name }}</h2>
            <p class="dev__title">{{ profile.short_intro}}</p>
            {% if profile.location %}
              <p class="dev__location">{{ profile.location }}</p>
            {% endif %}
            <br>
            {% if request.user.profile.id != profile.id %}
              <a href="{% url 'users:create_message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">
            {{ profile.bio }}
          </p>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Skills</h3>
          <div class="devInfo__skills">
            {% for skill in top_skills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{ skill.name }}</h4>
                <p class="devSkill__info">
                  {{ skill.description }}
                </p>
              </div>
            {% endfor %}
            <h3 class="devInfo__subtitle">Other Skills</h3>
            <div class="devInfo__otherSkills">
              {% for skill in other_skills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{ skill.name }}</small>
                </span>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Posts</h3>
          <div class="grid grid--two">
            {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'projects:project' project.id %}" class="project">
                    {% if project.featured_image %}
                      <img class="project__thumbnail" src="{{ project.image_url }}" alt="project thumbnail" />
                    {% else %}
                      <img class="project__thumbnail" src="{% static 'images/12.jpg' %}" alt="project thumbnail" />
                    {% endif %}
                    <div class="card__body">
                      <h3 class="project__title">{{ project.title }}</h3>
                      <p><a class="project__author" href="{% url 'users:user_profile' project.owner.id %}">By {{ project.owner.name }}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Positive
                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all|slice:"3" %}
                          <span class="tag tag--pill tag--main">
                            <small>{{ tag }}</small>
                          </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}