api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path("", views.get_routes),
    path("projects/", views.get_projects),
    path("projects/<str:pk>/", views.get_project),
    path("projects/<str:pk>/vote/", views.project_vote),
    path(
        "users/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"
    ),
    path(
        "users/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"
    ),
    path("remove-tag/", views.remove_tag)
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("projects.urls", namespace="projects")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("api/", include("api.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name="reset/reset_password.html"
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset/reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",  # by default
        auth_views.PasswordResetConfirmView.as_view(
            template_name="reset/reset_password_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",  # by default
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset/reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"

urlpatterns = [
    path(
        "",
        views.projects,
        name="projects",
    ),
    path(
        "project/<str:pk>/",
        views.project,
        name="project",
    ),
    path(
        "create_project/",
        views.create_project,
        name="create_project",
    ),
    path(
        "update_project/<str:pk>/",
        views.update_project,
        name="update_project",
    ),
    path(
        "delete_project/<str:pk>/",
        views.delete_project,
        name="delete_project",
    ),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"


urlpatterns = [
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
    path("", views.profiles, name="profiles"),
    path("profile/<str:pk>", views.user_profile, name="user_profile"),
    path("account/", views.user_account, name="user_account"),
    path("edit_account/", views.edit_account, name="edit_account"),
    path("create_skill/", views.create_skill, name="create_skill"),
    path("update_skill/<str:pk>/", views.update_skill, name="update_skill"),
    path("delete_skill/<str:pk>/", views.delete_skill, name="delete_skill"),
    path("inbox/", views.inbox, name="inbox"),
    path("message/<str:pk>/", views.view_message, name="message"),
    path(
        "create_message/<str:pk>/", views.create_message, name="create_message"
    ),

]

projects/models.py
from django.db import models
import uuid
from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(
        null=True, blank=True, default="default.jpg"
    )
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField("Tag", blank=True)  # "" - bcs Tag below
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = (
            "-vote_ratio",
            "-vote_total",
            "-created",
        )

    @property
    def image_url(self):
        try:
            url = self.featured_image.url
        except:
            url = ""
        return url


    # делаем лист, чтобы проверить, можем ли мы оставить ревью
    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list("owner__id", flat=True)
        return queryset

    @property
    def get_vote_count(self):
        reviews = self.review_set.all()
        up_votes = reviews.filter(value="up").count()
        total_votes = reviews.count()
        ratio = (up_votes / total_votes) * 100
        self.vote_total = total_votes
        self.vote_ratio = ratio
        self.save()


# comment
class Review(models.Model):
    VOTE_TYPE = (
        ("up", "Up vote"),
        ("down", "Down vote"),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # благодаря этому, только 1 ревью можно оставить
    class Meta:
        unique_together = [["owner", "project"]]
        ordering = ("-created",)

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.name


# class Follow(models.Model):
#     user = models.ForeignKey(
#         User,
#         on_delete=models.CASCADE,
#         related_name="follower",
#         verbose_name="Сталкер",
#     )
#     author = models.ForeignKey(
#         User,
#         on_delete=models.CASCADE,
#         related_name="following",
#         verbose_name="Тот кого сталкерят",
#     )

#     class Meta:
#         verbose_name = "Подписка"
#         verbose_name_plural = "Подписки"
#         constraints = models.UniqueConstraint(
#             fields=["user", "author"],
#             name="unique_followers",
#         )

projects/forms.py
from django.forms import ModelForm
from django import forms
from django.core.exceptions import ValidationError

from .models import Project, Review


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = [
            "title",
            "featured_image",
            "description",
            "demo_link",
            "source_link",
        ]  # мы вырезали tags, передаём их через html
        widgets = {"tags": forms.CheckboxSelectMultiple}

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        for k, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

        # self.fields["title"].widget.attrs.update(
        #     {"class": "input", "placeholder": "Add title"}
        # )
        # self.fields["description"].widget.attrs.update(
        #     {"class": "input", "placeholder": "Add description"}
        # )
        # self.fields["demo_link"].widget.attrs.update(
        #     {"class": "input", "placeholder": "Add demo link"}
        # )
        # self.fields["source_link"].widget.attrs.update(
        #     {"class": "input", "placeholder": "Add source link"}
        # )

    # делаем чтобы можно было выбрать не больше 3 тага
    # def clean_tags(self):
    #     value = self.cleaned_data["tags"]
    #     if len(value) > 3:
    #         raise ValidationError("You can't select more than 3 items.")
    #     # Always return a value to use as the new cleaned data, even if
    #     # this method didn't change it.
    #     return value


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            "value",
            "body",
        ]
        labels = {
            "value": "Place your vote",
            "body": "Add a comment with you vote",
        }

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)

        for k, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

projects/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages

from .utils import search_projects, paginator_projects
from .models import Project, Tag
from .forms import ProjectForm, ReviewForm


def projects(request):
    projects, search_query = search_projects(request)
    custom_range, projects = paginator_projects(request, projects, 3)
    context = {
        "projects": projects,
        "search_query": search_query,
        "custom_range": custom_range,
    }
    return render(request, "projects/projects.html", context)


def project(request, pk):
    project = Project.objects.get(id=pk)
    form = ReviewForm()
    if request.method == "POST":
        form = ReviewForm(request.POST)
        review = form.save(commit=False)
        review.project = project
        review.owner = request.user.profile
        review.save()
        project.get_vote_count
        # update later ^
        messages.success(request, "Your review was successfully submitted!")
        return redirect("projects:project", pk=project.id)
    context = {"project": project, "form": form}
    return render(request, "projects/single_project.html", context)


@login_required(login_url="users:login")
def create_project(request):
    profile = request.user.profile
    form = ProjectForm()
    if request.method == "POST":
        new_tags = (
            request.POST.get("new_tags").replace(",", " ").upper().split()
        )
        form = ProjectForm(
            request.POST or None,
            files=request.FILES or None,
        )
        if form.is_valid():
            project = form.save()
            project.owner = profile
            project.save()
            for tag in new_tags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)

            return redirect("projects:projects")
    context = {"form": form}
    return render(request, "projects/project_form.html", context)


@login_required(login_url="users:login")
def update_project(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    form = ProjectForm(
        request.POST or None,
        files=request.FILES or None,
        instance=project,
    )
    if request.method == "POST":
        new_tags = (
            request.POST.get("new_tags").replace(",", " ").upper().split()
        )
        form = ProjectForm(
            request.POST or None,
            files=request.FILES or None,
            instance=project,
        )
        if form.is_valid():
            project = form.save()
            for tag in new_tags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)
                
            return redirect("projects:projects")
    context = {"form": form, "project": project}
    return render(request, "projects/project_form.html", context)


@login_required(login_url="users:login")
def delete_project(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    if request.method == "POST":
        project.delete()
        return redirect("projects:projects")
    context = {"object": project}
    return render(request, "delete_object.html", context)


projects/templates/projects/project_form.html
{% extends "base.html" %}
{% block content %}

<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <a class="backButton" href="{% url 'users:user_account' %}">⇐</a>
      <br>
      <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form__field">
          <label for="formInput#text">{{ field.label }}</label>
          {{ field }}
        </div>
        {% endfor %}

        <div class="form__field">
          {% for tag in project.tags.all %}
          <div class="project-tag tag tag--pill tag--main" data-tag="{{tag.id}}" data-project="{{project.id}}">
            {{tag.name}}&#215;</div>
          {% endfor %}
        </div>

        <div class="form__field">
          <label for="formInput#text">Tags</label>
          <textarea name="new_tags" class="input" placeholder="Add tags here..."></textarea>
        </div>
        <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
      </form>
    </div>
  </div>
</main>

{% endblock content %}

projects/templates/projects/projects.html
{% extends "base.html" %}
{% load static %}
{% block title %} | Posts {% endblock %}
{% block content %}
  <main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Posts</span></h2>
        </div>
        <div class="hero-section__search">
          <form id="searchForm" class="form" action="{% url 'projects:projects' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Posts </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                placeholder="Search posts by title, author, tags" />
            </div>
            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">
          {% for project in projects %}
          <div class="column">
            <div class="card project">
              <a href="{% url 'projects:project' project.id %}" class="project">
               {% comment %}  {% if project.featured_image %} {% endcomment %}
                  <img class="project__thumbnail" src="{{ project.image_url }}" alt="project thumbnail" />
             {% comment %}    {% else %}
                  <img class="project__thumbnail" src="{% static 'images/12.jpg' %}" alt="project thumbnail" />
                {% endif %} {% endcomment %}
                <div class="card__body">
                  <h3 class="project__title">{{ project.title }}</h3>
                  <p><a class="project__author" href="{% url 'users:user_profile' project.owner.id %}">By {{ project.owner.name }}</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Positive
                    Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s"}})
                  </p>
                  <div class="project__tags">
                    {% for tag in project.tags.all %}
                      <span class="tag tag--pill tag--main">
                        <small>{{ tag }}</small>
                      </span>
                    {% endfor %}
                  </div>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
    {% include "paginator.html" with query_set=projects custom_range=custom_range %}
  </main>
{% endblock content %}
  

projects/templates/projects/single_project.html
{% extends "base.html" %}
{% load static %}
{% block title %} | Post {% endblock %}
{% block content %}
  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Tools & Stacks</h3>
          <div class="singleProject__toolStack">
            {% for tag in project.tags.all %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{ tag }}</small>
            </span>
            {% endfor %}
          </div>
          {% if project.source_link %}
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>
            Source Code
          </a>
          {% endif %}
          {% comment %} {% if project.demo_link %}
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>
            Source Code
          </a>
          {% endif %} {% endcomment %}
        </div>
        <div class="column column--2of3">
   {% comment %}        {% if project.featured_image %} {% endcomment %}
          <img class="singleProject__preview" src="{{ project.image_url }}" alt="portfolio thumbnail" />
{% comment %}           {% else %}
          <img class="singleProject__preview" src="{% static 'images/12.jpg' %}" alt="portfolio thumbnail" />
          {% endif %} {% endcomment %}

          <a href="{% url 'users:user_profile' project.owner.id %}" class="singleProject__developer">{{ project.owner.name }}</a>
          <h2 class="singleProject__title"> {{ project.title }}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>image.png
          <div class="singleProject__info">
            {{ project.description }}
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating">
              {{ project.vote_ratio }}% Postitive Feedback ({{ project.vote_total }}
              Vote{{ project.vote_total|pluralize:"s"}})
            </h5>
            {% if request.user.profile.id in project.reviewers %}
              <p>You have already submitted your review for this project</p>
            {% elif request.user.profile == project.owner %}
              <p>You cannot review your own work</p>
            {% elif request.user.is_authenticated %}
              <form class="form" action="{% url 'projects:project' project.id %}" method="POST">          
                {% csrf_token %}
                {% for field in form %}
                  <div class="form__field">
                    <label for="formInput#textarea">pizda</label>
                    {{ field.label }}<br>
                    {{ field }}
                  </div>
                {% endfor %}
                <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
              </form>
            {% else %}
              <a href="{% url 'users:login' %}?next={{ request.path }}">Please login to leave a review</a>
            {% endif %}
            <div class="commentList">
              {% for review in project.review_set.all %}
                {% if review.body %}
                  <div class="comment">
                    <a href="{% url 'users:user_profile' review.owner.id %}">
                      <img class="avatar avatar--md"
                        src="{{ review.owner.image_url }}" alt="user" />
                    </a>
                    <div class="comment__details">
                
                      <a href="{% url 'users:user_profile' review.owner.id %}" class="comment__author">{{ review.owner.name }}</a>
                      <p class="comment__info">
                        {{ review.body|linebreaksbr }}
                      </p>

                      <a> {{ review.created }} </a> 
                    </div>
                  </div>
                {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>
{% endblock content %}